### ISSUE TITLE
running error 

### ISSUE THREAD

**Issue by RenzoGamero** [CodeReclaimers/btce-bot#10]
Running; press Ctrl-C to stop
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/btce_api-0.3.1-py2.7.egg/btceapi/trade.py:180: UserWarning: The nonce in the key file is out of date; attempting to correct.
2017/03/28 19:58:41 - Error in handler <bound method RangeTrader.onNewDepth of <__main__.RangeTrader object at 0x102d11690>> for ltc_usd depth
2017/03/28 20:00:57 - Error while retrieving ltc_usd depth
i have this two types of error. I put the "Key" , "Secret"  and nonce =1 
any idea ?

**Comment by CodeReclaimers** [comment]
I'm not sure, but this is probably related to #9; once you get  the nonce issue sorted out, please let me know if you're still getting that onNewDepth error.
