### ISSUE TITLE
new error when attempting to trade?

### ISSUE THREAD

**Issue by Sillerd** [CodeReclaimers/btce-bot#8]
Error in handler <bound method RangeTrader.onNewDepth of <__main__.RangeTrader object at 0x7f56a9e8cc90>> for ltc_usd depth

**Comment by CodeReclaimers** [comment]
Apologies for not getting to this for so, so long.  I'm guessing you either found a solution or moved on to another library, but please feel free to reopen this issue or start a new one if this is still something you need a solution for.
